name: libdwarf CI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"
      - name: autoreconf
        working-directory: ./libdwarf-code
        run: |
          brew install automake
          autoreconf --warnings=all --install --verbose --force
      - name: configure
        working-directory: ./libdwarf-code
        run: ./configure --disable-debug --enable-shared --disable-nonshared --disable-dependency-tracking --disable-silent-rules CFLAGS=-O2